operators:
  - id: negative_examples
    config:
      type: hf_source
      dataset: mlfoundations-dev/SCP_40k_R1_with_OT_verified
      split: train
  - id: inference_examples
    config:
      type: hf_source
      dataset: open-thoughts/Open-Thoughts-114k
      split: train
  - id: load_seed_code_multiple_samples_all_scale_up_16K
    config:
      type: hf_source
      dataset: mlfoundations-dev/seed_code_multiple_samples_all_scale_up_16K
      split: train 
  - id: keep_only_converstations_load_seed_code_multiple_samples_all_scale_up_16K
    config:
      type: function
      function: data_strategies.commons.keep_only_columns
      function_config:
        columns_to_keep: [conversations]
    input_ids:
      - load_seed_code_multiple_samples_all_scale_up_16K
  - id: load_seed_math_multiple_samples_scale_up_majority_consensus_llm_verifier_real_run_16K
    config:
      type: hf_source
      dataset: mlfoundations-dev/seed_math_multiple_samples_scale_up_majority_consensus_llm_verifier_real_run_16K
      split: train
  - id: keep_only_converstations_load_seed_math_multiple_samples_scale_up_majority_consensus_llm_verifier_real_run_16K  
    config:
      type: function
      function: data_strategies.commons.keep_only_columns
      function_config:
        columns_to_keep: [conversations]
    input_ids:
      - load_seed_math_multiple_samples_scale_up_majority_consensus_llm_verifier_real_run_16K
  - id: load_fasttext_mixing_domains_top_7_code
    config:
      type: hf_source
      dataset: mlfoundations-dev/fasttext_mixing_domains_top_7_code
      split: train
  - id: keep_only_converstations_load_fasttext_mixing_domains_top_7_code
    config:
      type: function
      function: data_strategies.commons.keep_only_columns
      function_config:
        columns_to_keep: [conversations]
    input_ids:
      - load_fasttext_mixing_domains_top_7_code
  - id: load_fasttext_mixing_domains_top_2
    config:
      type: hf_source
      dataset: mlfoundations-dev/fasttext_mixing_domains_top_2
      split: train
  - id: keep_only_converstations_load_fasttext_mixing_domains_top_2
    config:
      type: function
      function: data_strategies.commons.keep_only_columns
      function_config:
        columns_to_keep: [conversations]
    input_ids:
      - load_fasttext_mixing_domains_top_2
  - id: positive_examples
    config:
      type: mix
    input_ids:
      - keep_only_converstations_load_seed_code_multiple_samples_all_scale_up_16K
      - keep_only_converstations_load_seed_math_multiple_samples_scale_up_majority_consensus_llm_verifier_real_run_16K
      - keep_only_converstations_load_fasttext_mixing_domains_top_7_code
      - keep_only_converstations_load_fasttext_mixing_domains_top_2
  - id: rename_columns
    config:
      type: function
      function: data_strategies.commons.change_tags
      function_config:
        conversation_column: conversations
        tags_to_change: 
          human: user
          user: user
          gpt: assistant
          assistant: assistant
    input_ids:
      - positive_examples
  - id: formatted_pos_ex
    config:
      type: function
      function: data_strategies.32b_exploit.filter_out_scp.utils.conversation_array_to_string
      function_config:
        conversation_column: conversations
        flat_column_name: formatted_conversations
    input_ids:
      - rename_columns
  - id: formatted_neg_ex
    config:
      type: function
      function: data_strategies.32b_exploit.filter_out_scp.utils.conversation_array_to_string
      function_config:
        conversation_column: conversations
        flat_column_name: formatted_conversations
    input_ids:
      - negative_examples
  - id: formatted_inference_ex
    config:
      type: function
      function: data_strategies.32b_exploit.filter_out_scp.utils.conversation_array_to_string
      function_config:
        conversation_column: conversations
        flat_column_name: formatted_conversations 
    input_ids:
      - inference_examples
  - id: pos_strings
    config:
      type: function
      function: data_strategies.commons.select_columns
      function_config:
        columns: [formatted_conversations]
    input_ids:
      - formatted_pos_ex
  - id: neg_strings
    config:
      type: function
      function: data_strategies.commons.select_columns
      function_config:
        columns: [formatted_conversations]
    input_ids:
      - formatted_neg_ex
  - id: inference_strings
    config:
      type: function
      function: data_strategies.commons.select_columns
      function_config:
        columns: [formatted_conversations]
    input_ids:  
      - formatted_inference_ex
  - id: train_fasttext_classifier
    config:
      type: train_fasttext
      text_column: formatted_conversations
      positive_input_ids:
        - pos_strings
      negative_input_ids:
        - neg_strings
      dim: 256
      epoch: 10
      lr: 0.01
      word_ngrams: 3
      min_count: 3
      hf_repo_id: mlfoundations-dev/scp_vs_seed_data_fasttext_classifier
    input_ids:
      - pos_strings
      - neg_strings
  - id: classify_fasttext
    config:
      type: fasttext
      hf_repo_id: mlfoundations-dev/scp_vs_seed_data_fasttext_classifier
      input_column: formatted_conversations
      target_label: "__label__QA_doc"
      filter_threshold: 0.5
    input_ids:
      - inference_strings