operators:
- id: load_stackexchange_codegolf
  config:
    type: load_preexisting
    framework_name: stackexchange_code_golf_reorg_cache
- id: rename_task_column_stackexchange_codegolf
  config:
    type: function
    function: data_strategies.commons.force_rename_columns
    function_config:
      column_maps:
        instruction: question
  input_ids:
  - load_stackexchange_codegolf



- id: hf_source_bad_seed_code_reflect
  config:
    type: load_preexisting
    framework_name: reflection
- id: hf_source_bad_seed_code_octo
  config:
    type: load_preexisting
    framework_name: octopack_sft
- id: rename_task_column
  config:
    type: function
    function: data_strategies.commons.force_rename_columns
    function_config:
      column_maps:
        instruction_seed: question
  input_ids:
  - hf_source_bad_seed_code_octo
  - hf_source_bad_seed_code_reflect
- id: train_fasttext_classifier
  config:
    type: train_fasttext
    text_column: question
    positive_input_ids:
      - rename_task_column_stackexchange_codegolf
    negative_input_ids:
      - rename_task_column
    dim: 256
    epoch: 3
    lr: 0.1
    word_ngrams: 2
    min_count: 3
    hf_repo_id: mlfoundations-dev/instruction_filtering_fast_text_classifier_seed_code_best_stackexchange_codegolf
  input_ids:
    - rename_task_column_stackexchange_codegolf
    - rename_task_column