operators:
- id: hf_source_numina
  config:
    type: hf_source
    dataset: AI-MO/NuminaMath-CoT
    split: train
- id: select_amc_aime
  config:
    type: function
    function: data_strategies.commons.select_rows
    function_config:
      conditions:
        source: amc_aime
  input_ids:
    - hf_source_numina
- id: select_aops
  config:
    type: function
    function: data_strategies.commons.select_rows
    function_config:
      conditions:
        source: aops_forum
  input_ids:
    - hf_source_numina
- id: rename_task_column_numina
  config:
    type: function
    function: data_strategies.commons.force_rename_columns
    function_config:
      column_maps:
        problem: question
  input_ids:
  - select_amc_aime
  - select_aops
- id: hf_source_bad_seed_math
  config:
    type: load_preexisting
    framework_name: seed_math_formulas
- id: rename_task_column
  config:
    type: function
    function: data_strategies.commons.force_rename_columns
    function_config:
      column_maps:
        instruction_seed: question
  input_ids:
  - hf_source_bad_seed_math
- id: train_fasttext_classifier
  config:
    type: train_fasttext
    text_column: question
    positive_input_ids:
      - rename_task_column_numina
    negative_input_ids:
      - rename_task_column
    dim: 256
    epoch: 3
    lr: 0.1
    word_ngrams: 2
    min_count: 3
    hf_repo_id: mlfoundations-dev/instruction_filtering_fast_text_classifier_seed_math_worst_3
  input_ids:
    - rename_task_column
    - rename_task_column_numina