operators:
- id: load_preexisting_automath
  config:
    type: load_preexisting
    framework_name: seed_math_automathtext
- id: rename_task_column_positive_automath
  config:
    type: function
    function: data_strategies.commons.force_rename_columns
    function_config:
      column_maps:
        instruction_seed: question
  input_ids:
  - load_preexisting_automath
- id: load_preexisting_openr1math
  config:
    type: hf_source
    dataset: open-r1/OpenR1-Math-220k
    split: train
- id: rename_task_column_positive_openr1math
  config:
    type: function
    function: data_strategies.commons.force_rename_columns
    function_config:
      column_maps:
        problem: question
  input_ids:
  - load_preexisting_openr1math
- id: load_preexisting_olympiad
  config:
    type: hf_source
    dataset: brando/olympiad-bench-imo-math-boxed-825-v2-21-08-2024
    split: all
- id: rename_task_column_positive_olympiad
  config:
    type: function
    function: data_strategies.commons.force_rename_columns
    function_config:
      column_maps:
        problem: question
  input_ids:
  - load_preexisting_olympiad
- id: load_preexisting_tigerlab
  config:
    type: load_preexisting
    framework_name: seed_math_tiger_lab_math
- id: rename_task_column_positive_tigerlab
  config:
    type: function
    function: data_strategies.commons.force_rename_columns
    function_config:
      column_maps:
        instruction_seed: question
  input_ids:
  - load_preexisting_tigerlab

- id: load_preexisting_s1
  config:
    type: hf_source
    dataset: mlfoundations-dev/s1K_reformat
    split: train

- id: hf_source_bad_seed_math
  config:
    type: load_preexisting
    framework_name: seed_math_math_instruct
- id: rename_task_column
  config:
    type: function
    function: data_strategies.commons.force_rename_columns
    function_config:
      column_maps:
        instruction_seed: question
  input_ids:
  - hf_source_bad_seed_math
- id: train_fasttext_classifier
  config:
    type: train_fasttext
    text_column: question
    positive_input_ids:
      - rename_task_column_positive_automath
      - rename_task_column_positive_openr1math
      - rename_task_column_positive_olympiad
      - rename_task_column_positive_tigerlab
      - load_preexisting_s1
    negative_input_ids:
      - rename_task_column
    dim: 256
    epoch: 3
    lr: 0.1
    word_ngrams: 2
    min_count: 3
    hf_repo_id: mlfoundations-dev/instruction_filtering_fast_text_classifier_seed_math_best_mix
  input_ids:
    - rename_task_column
    - rename_task_column_positive_automath
    - rename_task_column_positive_openr1math
    - rename_task_column_positive_olympiad
    - rename_task_column_positive_tigerlab
    - load_preexisting_s1