bf16: true
cutoff_len: 2048
dataset: microsoft/orca-agentinstruct-1M-v1
dataset_dir: ""
ddp_timeout: 180000000
deepspeed: dcft/train/zero3.json
do_train: true
enable_liger_kernel: true
eval_strategy: 'no'
finetuning_type: full
global_batch_size: 512
gradient_accumulation_steps: 4
gradient_checkpointing: true
hub_model_id: mlfoundations-dev/meta-llama/Meta-Llama-3.1-8B_microsoft_orca-agentinstruct-1M-v1_2.00E-06_8_4_1
learning_rate: 2.0e-06
logging_steps: 10
lr_scheduler_type: cosine
messages: messages
model_name_or_path: meta-llama/Meta-Llama-3.1-8B
neat_packing: true
num_train_epochs: 1
output_dir: meta-llama/Meta-Llama-3.1-8B_microsoft_orca-agentinstruct-1M-v1_2.00E-06_8_4_1
overwrite_cache: true
overwrite_output_dir: true
packing: true
per_device_train_batch_size: 8
plot_loss: true
preprocessing_num_workers: 32
push_to_db: false
push_to_hub: false
report_to: wandb
run_name: meta-llama/Meta-Llama-3.1-8B_microsoft_orca-agentinstruct-1M-v1_2.00E-06_8_4_1
save_strategy: epoch
stage: sft
template: llama3
warmup_ratio: 0.1
