include_hp: dcft/train/hp_settings/hritik.yaml

dataset_dir: ONLINE
dataset: mlfoundations-dev/dcft-orca-agentinstruct-1M-v1-cleaned
template: llama3
formatting: sharegpt
messages: messages

per_device_train_batch_size: 8      # Can change depending on hardware
gradient_accumulation_steps: 2      # Can change depending on number of GPUs

output_dir: "/data4/dcft/experiments/train/checkpoints/dcft-orca-agentinstruct-1M-v1-cleaned"
run_name: dcft-orca-agentinstruct-1M-v1-cleaned
hub_model_id: mlfoundations-dev/dcft-orca-agentinstruct-1M-v1-cleaned
report_to: wandb
push_to_db: true
push_to_hub: true
