bf16: true
cutoff_len: 512
dataset: mlfoundations-dev/alpaca_en_5120
dataset_dir: OFFLINE_CACHE
datasets_cache_dir: /leonardo_work/EUHPC_E03_068/DCFT_shared/hf_cache/datasets
ddp_timeout: 180000000
deepspeed: dcft/train/zero1.json
do_train: true
enable_liger_kernel: true
eval_strategy: epoch
finetuning_type: full
formatting: alpaca
global_batch_size: 128
gradient_accumulation_steps: 2
gradient_checkpointing: true
hub_model_id: mlfoundations-dev/mistral_alpaca_sft_sample
learning_rate: 2.0e-05
logging_steps: 10
lr_scheduler_type: cosine
model_name_or_path: /leonardo_work/EUHPC_E03_068/DCFT_shared/hf_cache/models/models--meta-llama--Llama-3.1-8B-Instruct/snapshots/0e9e39f249a16976918f6564b8830bc894c89659
neat_packing: true
num_train_epochs: 1.0
output_dir: /leonardo_work/EUHPC_E03_068/DCFT_shared/outputs/mlfoundations-dev_alpaca_en_5120_meta-llama_Llama-3.1-8B-Instruct_sample
overwrite_cache: true
overwrite_output_dir: true
packing: true
per_device_train_batch_size: 8
plot_loss: true
preprocessing_num_workers: 16
push_to_db: false
push_to_hub: false
report_to: wandb
run_name: mlfoundations-dev_alpaca_en_5120_meta-llama_Llama-3.1-8B-Instruct_sample
save_strategy: epoch
stage: sft
template: alpaca
val_size: 0.05
warmup_ratio: 0.1
