include_hp: dcft/train/hp_settings/hritik.yaml

dataset_dir: ONLINE
dataset: mlfoundations-dev/oh-dcft-v1.2_no-curation_gpt-4o-mini
template: llama3
messages: conversations
formatting: sharegpt

per_device_train_batch_size: 8      # Can change depending on hardware
gradient_accumulation_steps: 1      # Can change depending on number of GPUs

output_dir: "/data4/dcft/experiments/train/checkpoints/oh-dcft-v1.2_no-curation_gpt-4o-mini"
run_name: oh-dcft-v1.2_no-curation_gpt-4o-mini
hub_model_id: mlfoundations-dev/oh-dcft-v1.2_no-curation_gpt-4o-mini
report_to: wandb
push_to_db: true
push_to_hub: true
