include_hp: dcft/train/hp_settings/hritik.yaml

dataset_dir: ONLINE
dataset: mlfoundations-dev/oh_v3.1_leave_out_non_v1.2_subsets
template: llama3
messages: conversations
formatting: sharegpt

per_device_train_batch_size: 8      # Can change depending on hardware
gradient_accumulation_steps: 2      # Can change depending on number of GPUs

output_dir: "/data4/dcft/experiments/train/checkpoints/oh_v3.1_leave_out_non_v1.2_subsets"
run_name: oh_v3.1_leave_out_non_v1.2_subsets
hub_model_id: mlfoundations-dev/oh_v3.1_leave_out_non_v1.2_subsets
report_to: wandb
push_to_db: true
push_to_hub: true
