include_hp: dcft/train/hp_settings/hritik.yaml

dataset_dir: ONLINE
dataset: allenai/tulu-3-sft-mixture
formatting: sharegpt
messages: messages
role_tag: role
content_tag: content
user_tag: user
assistant_tag: assistant

per_device_train_batch_size: 8      # Can change depending on hardware
gradient_accumulation_steps: 2      # Can change depending on number of GPUs

output_dir: "/data4/dcft/experiments/train/checkpoints/tulu-3-sft-mixture"
run_name: tulu-3-sft-mixture
hub_model_id: mlfoundations-dev/tulu-3-sft-mixture
report_to: wandb
push_to_db: true
push_to_hub: true
