include_hp: dcft/train/hp_settings/hritik.yaml

dataset_dir: ONLINE
dataset: mlfoundations-dev/tulu-v.3.9-mix-preview-noncommercial
template: llama3
messages: messages
formatting: sharegpt

per_device_train_batch_size: 8      # Can change depending on hardware
gradient_accumulation_steps: 2      # Can change depending on number of GPUs

output_dir: "/data4/dcft/experiments/train/checkpoints/tulu-v.3.9-v0"
run_name: tulu-v.3.9-v0
hub_model_id: mlfoundations-dev/tulu-v.3.9-v0
report_to: wandb
push_to_db: true
push_to_hub: true
