operators:
  - id: create_urls
    config:
      type: function
      function: data_strategies.32b_exploit.seed_pdf_parser.utils.download_digital_corpora
      function_config:
        urls:
          - "https://digitalcorpora.s3.amazonaws.com/corpora/files/CC-MAIN-2021-31-PDF-UNTRUNCATED/zipfiles/0000-0999/0000.zip"
  - id: reduce_to_sample_pages_for_annotation
    config:
      type: function
      function: data_strategies.32b_exploit.seed_pdf_parser.utils.sub_sample_page_per_url
    input_ids:
      - create_urls
  - id: filter_qa_pdfs
    config:
      type: completions
      model: gpt-4o-mini
      map: binary_classifier
      map_config:
        user_message: |
          Yes or No, given the sample of pages from the pdf below, will the PDF include questions involving Math, Science, or Code? Specifically we are interested in if this pdf is a textbook, solutions manual, competition exam, test, study guide, etc. such that questions like the example given may be found in the full PDF.
          
          Example question:
          Find the integrals: (a) ∫ sinh² x cosh² x dx; (b) ∫ dx sinh x cosh x. Find the integral ∫ sinh² x cosh² x dx.
          
          The example is math, but we are interested in science, math, and coding questions.
          
          Sampled PDF text:
          {{sampled_pdf_text}}
        output_column: contains_math_sci_code_content
      temperature: 0.0  # From stage 1
      top_p: 1.0
      presence_penalty: 0.0
    input_ids:
      - reduce_to_sample_pages_for_annotation
  - id: filter_out_good_pdfs
    config:
      type: function
      function: data_strategies.commons.select_rows
      function_config:
        conditions:
          contains_math_sci_code_content: False
    input_ids:
      - filter_qa_pdfs
  - id: filter_original_pages
    config:
      type: function
      function: data_strategies.32b_exploit.seed_pdf_parser.utils.filter_pdfs_by_page_classification
      function_config:
        to_filter_identifier_column: pdf_file
        classifications_identifier_column: pdf_file
      input_dataset_map:
        dataset_with_pages: create_urls
        dataset_of_filtered_pdfs: filter_out_good_pdfs
    input_ids:
      - create_urls
      - filter_out_good_pdfs
  - id: good_pdfs
    config:
      type: function
      function: data_strategies.32b_exploit.seed_pdf_parser.utils.create_url_dataset
      function_config:
        urls:
          - "https://uwaterloo.ca/chemistry/sites/default/files/uploads/documents/avogadro-exam-solution-2010.pdf"
          - "https://uwaterloo.ca/chemistry/sites/default/files/uploads/documents/avogadro-exam-solution-2009.pdf"
          - "https://uwaterloo.ca/chemistry/sites/default/files/uploads/documents/avogadro-exam-solution-2008.pdf"
          - "https://uwaterloo.ca/chemistry/sites/default/files/uploads/documents/avogadro-exam-solution-2007.pdf"
          - "https://uwaterloo.ca/chemistry/sites/default/files/uploads/documents/chem-13-news-solution-2011.pdf"
          - "https://uwaterloo.ca/chemistry/sites/default/files/uploads/documents/chem-13-news-exam-solution-2010.pdf"
          - "https://uwaterloo.ca/chemistry/sites/default/files/uploads/documents/chem-13-news-exam-solution-2009.pdf"
          - "https://uwaterloo.ca/chemistry/sites/default/files/uploads/documents/chem-13-news-exam-solution-2008.pdf"
          - "https://uwaterloo.ca/chemistry/sites/default/files/uploads/documents/chem-13-news-exam-solution-2007.pdf"
          - "https://www.press.muni.cz/media/3019066/answers_to_all_questions.pdf"
          - "https://public.wsu.edu/~thorglab/biol301/exams/finalkey.pdf"
          - "https://people.bu.edu/msoren/BI515_2014/Exam1key.pdf"
          - "https://facultystaff.richmond.edu/~lrunyenj/bio201/04bio201%20exam%201%20key.pdf"
          - "https://www.usabo-trc.org/sites/default/files/images/pdf/exams/semifinal-answers/2011-semifinal-answers.pdf"
          - "https://sites.science.oregonstate.edu/chemistry/courses/ch411/restrict2/ch411%20F11%20final%20key%20.pdf"
          - "https://www.mit.edu/~anugrah/files/MockIChOSolutions.pdf"
          - "https://www.mit.edu/~anugrah/files/2012CChOLocalSoln.pdf"
          - "https://www.cheminst.ca/wp-content/uploads/2022/11/CCC-PtA-2022-ENG-final-ANSWERS.pdf"
          - "https://www.cheminst.ca/wp-content/uploads/2022/12/Canadian-Chemistry-Olympiad-2022-EN_key.pdf"
          - "https://www.cheminst.ca/wp-content/uploads/2022/01/CCC-PtA-2021-ENG-ANSWERS.pdf"
          - "https://www.cheminst.ca/wp-content/uploads/2021/01/CCC-PtA-2020-ENG-ANSWERS-revised-COVID19.pdf"
          - "https://www.cheminst.ca/wp-content/uploads/2019/11/CCC-2019-PtA-answers.pdf"
          - "https://www.cheminst.ca/wp-content/uploads/2019/11/CCC-2017-PtA-answers-EN.pdf"
          - "https://www.cheminst.ca/wp-content/uploads/2019/11/CCC-2018-PtA-answers-EN.pdf"
          - "https://www.cheminst.ca/wp-content/uploads/2019/11/CCC-2016-PtA-answers-EN.pdf"
          - "https://www.cheminst.ca/wp-content/uploads/2019/11/CCC-2015-PtA-answers-EN.pdf"
          - "https://www.cheminst.ca/wp-content/uploads/2019/11/CCC-2014-PtA-answers-EN.pdf"
          - "https://www.ttcho.com/_files/ugd/988b76_e3d21fc42bb24de4959d7250f0cfcb3a.pdf"
          - "https://www.ttcho.com/_files/ugd/988b76_01ceeff230b24cbbb0125b2bfa3f3475.pdf"
          - "https://www.ttcho.com/_files/ugd/988b76_48944f6ace684143bfdc9080fca59862.pdf"
          - "https://www.ttcho.com/_files/ugd/988b76_ba0cb3177d05436da273a400a037ed01.pdf"
          - "http://chemistryrace.com/wp-content/uploads/2025/02/ChR_2025_answer_booklet.pdf"
          - "http://chemistryrace.com/wp-content/uploads/2024/02/ChR_2024_answer_booklet.pdf"
          - "http://chemistryrace.com/wp-content/uploads/2023/02/chemistry_race_2023_answers-book.pdf"
          - "http://chemistryrace.com/wp-content/uploads/2022/02/cambridge_chemistry_race_2022_answers.pdf"
          - "http://chemistryrace.com/wp-content/uploads/2021/02/Chemistry_Race_2021_Questions_and_Solutions.pdf"
          - "https://chemistryrace.soc.srcf.net/wp-content/uploads/2020/02/Chemistry_Race_2020_Questions_and_Solutions.pdf"
          - "https://biolympiads.com/wp-content/uploads/2015/01/2003_OpenExam_AnswerKey2.pdf"
          - "http://biolympiads.com/wp-content/uploads/2015/01/2004_OpenExam_AnswerKey4.pdf"
          - "http://biolympiads.com/wp-content/uploads/2015/01/2005_OpenExam_AnswerKey1.pdf"
          - "http://biolympiads.com/wp-content/uploads/2015/01/2006_OpenExam_AnsKey2.pdf"
          - "http://biolympiads.com/wp-content/uploads/2015/01/2007_OpenExam_AnsKey1.pdf"
          - "http://biolympiads.com/wp-content/uploads/2015/01/2008_OpenExam_AnsKey1.pdf"
          - "http://biolympiads.com/wp-content/uploads/2015/01/2009_OpenExam_AnsKey1.pdf"
          - "http://biolympiads.com/wp-content/uploads/2015/01/2010_OpenExam_AnsKey3.pdf"
          - "http://biolympiads.com/wp-content/uploads/2015/01/2011_OpenExam_AnsKey.pdf"
          - "http://biolympiads.com/wp-content/uploads/2015/01/2012_OpenExam_AnsKey2.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2024/02/ASOE-Chemistry-2023-Exam-Paper-with-Answers.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2023/05/ASOE-Chemistry-2022-ASDAN-answers.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2023/05/ASOE_Chemistry_2021_answers_reduced-FS.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2020-asoe-chemistry-exam-answers.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2019-asoe-chemistry-exam-answers.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2018-asoe-chemistry-exam-answers.pdf"
          - "https://www.andrews.edu/~rwright/physics/OpenStax%20Physics-Student%20Solution%20Manual.pdf"
          - "https://reanphysics.wordpress.com/wp-content/uploads/2018/11/raymond_a-_serway_john_w-_jewett_student_solutibookzz-org.pdf"
          - "https://carrollscaveofknowledge.weebly.com/uploads/2/0/2/8/20287891/physics_11_regular_year_solutions_manual.pdf"
          - "https://doctor2019.jumedicine.com/wp-content/uploads/sites/10/2019/09/Giancoli-Physics-Principles-With-Applications-7th-c2014-solutions-ISM.pdf"
          - "https://ia801305.us.archive.org/8/items/ProblemsInCalculusOfOneVariableI.A.Maron/Problems%20in%20Calculus%20of%20One%20Variable%20-%20I.%20A.%20Maron.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2017-asoe-chemistry-exam.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2016-asoe-chemistry-exam.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2015-asoe-chemistry-exam.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2014-asoe-chemistry-exam.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2013-asoe-chemistry-exam.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2012-asoe-chemistry-exam.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2011-asoe-chemistry-exam.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2010-asoe-chemistry-exam.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2009-asoe-chemistry-exam.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2008-asoe-chemistry-exam.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2007-asoe-chemistry-exam.pdf"
          - "https://jeeadv.ac.in/past_qps/2007_1.pdf"
          - "https://jeeadv.ac.in/past_qps/2007_2.pdf"
          - "https://jeeadv.ac.in/past_qps/2008_1.pdf"
          - "https://jeeadv.ac.in/past_qps/2008_2.pdf"
          - "https://jeeadv.ac.in/past_qps/2009_1.pdf"
          - "https://jeeadv.ac.in/past_qps/2009_2.pdf"
          - "https://jeeadv.ac.in/past_qps/2010_1.pdf"
          - "https://jeeadv.ac.in/past_qps/2010_2.pdf"
          - "https://jeeadv.ac.in/past_qps/2011_1.pdf"
          - "https://jeeadv.ac.in/past_qps/2011_2.pdf"
          - "https://jeeadv.ac.in/past_qps/2012_1.pdf"
          - "https://jeeadv.ac.in/past_qps/2012_2.pdf"
          - "https://jeeadv.ac.in/past_qps/2013_1.pdf"
          - "https://jeeadv.ac.in/past_qps/2013_2.pdf"
          - "https://jeeadv.ac.in/past_qps/2014_1.pdf"
          - "https://jeeadv.ac.in/past_qps/2014_2.pdf"
          - "https://jeeadv.ac.in/past_qps/2015_1.pdf"
          - "https://jeeadv.ac.in/past_qps/2015_2.pdf"
          - "https://jeeadv.ac.in/past_qps/2017_1.pdf"
          - "https://jeeadv.ac.in/past_qps/2017_2.pdf"
          - "https://jeeadv.ac.in/past_qps/2018_1.pdf"
          - "https://jeeadv.ac.in/past_qps/2018_2.pdf"
          - "https://jeeadv.ac.in/past_qps/2019_1_English.pdf"
          - "https://jeeadv.ac.in/past_qps/2019_2_English.pdf"
          - "https://jeeadv.ac.in/past_qps/2020_1_English.pdf"
          - "https://jeeadv.ac.in/past_qps/2020_2_English.pdf"
          - "https://jeeadv.ac.in/past_qps/2021_1_English.pdf"
          - "https://jeeadv.ac.in/past_qps/2021_2_English.pdf"
          - "https://jeeadv.ac.in/past_qps/2022_1_English.pdf"
          - "https://jeeadv.ac.in/past_qps/2022_2_English.pdf"
          - "https://jeeadv.ac.in/past_qps/2023_1_English.pdf"
          - "https://jeeadv.ac.in/past_qps/2023_2_English.pdf"
          - "https://jeeadv.ac.in/past_qps/2024_1_English.pdf"
          - "https://jeeadv.ac.in/past_qps/2024_2_English.pdf"
          - "https://ia600608.us.archive.org/19/items/IrodovProblemsInGeneralPhysics/Irodov-Problems_in_General_Physics.pdf"
          - "https://ia601305.us.archive.org/8/items/ProblemsInCalculusOfOneVariableI.A.Maron/Problems%20in%20Calculus%20of%20One%20Variable%20-%20I.%20A.%20Maron.pdf"
          - "https://blogmedia.testbook.com/kmat-kerala/wp-content/uploads/2023/06/physical-chemistry-by-p-bahadur-5113ed32.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2023-ASOE-Physics-Past-Paper-ASI.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2022-ASOE-Physics.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2021-ASOE-Physics.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2020-asoe-physics-exam.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2019-asoe-physics-exam.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2017-asoe-physics-exam.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2016-asoe-physics-exam.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2015-asoe-physics-exam.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2014-asoe-physics-exam.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2013-asoe-physics-exam.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2012-asoe-physics-exam.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2011-asoe-physics-exam.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2010-Physics-NQE-paper-FINAL.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2010-Physics-NQE-paper-FINAL.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2008-asoe-physics-exam.pdf"
          - "https://www.asi.edu.au/wp-content/uploads/2022/12/2007-asoe-physics-exam.pdf"
          - "http://algorithmics.lsi.upc.edu/docs/Dasgupta-Papadimitriou-Vazirani.pdf"
          - "https://biocomp.utoronto.ca/files/2024/05/Exam2024.pdf"
          - "https://biocomp.utoronto.ca/files/2023/10/biocomp-exam-2019.pdf"
          - "https://biocomp.utoronto.ca/files/2023/10/biocomp-exam-2018_0.pdf"
          - "https://biocomp.utoronto.ca/files/2023/10/biocomp-exam-2017.pdf"
          - "https://biocomp.utoronto.ca/files/2023/10/biocomp-exam-2016.pdf"
          - "https://biocomp.utoronto.ca/files/2023/10/biocomp-exam-2015.pdf"
          - "https://www.andrews.edu/~rwright/physics/OpenStax%20Physics-Student%20Solution%20Manual.pdf"
          - "https://reanphysics.wordpress.com/wp-content/uploads/2018/11/raymond_a-_serway_john_w-_jewett_student_solutibookzz-org.pdf"
          - "https://carrollscaveofknowledge.weebly.com/uploads/2/0/2/8/20287891/physics_11_regular_year_solutions_manual.pdf"
          - "https://doctor2019.jumedicine.com/wp-content/uploads/sites/10/2019/09/Giancoli-Physics-Principles-With-Applications-7th-c2014-solutions-ISM.pdf"
          - "http://lib.ysu.am/disciplines_bk/ea4b336028cd91ba7265865d8fde153c.pdf"
          - "https://www.sfcollege.edu/_media/Assets/sf/placement/files/Chemistry%20Practice%20Placement%20Exam.pdf"
          - "https://www.pvamu.edu/chemistry/wp-content/uploads/sites/26/_01_pract_Test.pdf"
          - "https://sccollege.edu/students/studentservices/counseling/Shared%20Documents/Chem%20Placement%20Practice%20Exam%202023.pdf"
          - "https://www.csn.edu/sites/default/files/documents/department-documents/department-of-physical-sciences/chemplacementtestpractice.pdf"
          - "https://www.mc3.edu/admissions/applying-to-mccc/testing-and-assessment/assets/biology-placement-test.pdf"
  - id: good_pdfs_get_pdf_bytes
    config:
      type: function
      function: data_strategies.32b_exploit.seed_pdf_parser.utils.download_pdfs
    input_ids:
      - good_pdfs
  - id: good_pdfs_process_pdfs
    config:
      type: function
      function: data_strategies.32b_exploit.seed_pdf_parser.utils.get_all_page_counts
    input_ids:
      - good_pdfs_get_pdf_bytes
  - id: good_pdf_get_page_bytes
    config:
      type: function
      function: data_strategies.32b_exploit.seed_pdf_parser.utils.expand_and_extract_pages_raw_text
      function_config:
        page_count_column: page_count
    input_ids:
      - good_pdfs_process_pdfs
  - id: rename_good_pdf_columns
    config:
      type: function
      function: data_strategies.commons.force_rename_columns
      function_config:
        column_maps:
          pdf_text: cleaned_text
    input_ids:
      - good_pdf_get_page_bytes
  - id: rename_bad_pdf_columns
    config:
      type: function
      function: data_strategies.commons.force_rename_columns
      function_config:
        column_maps:
          text: cleaned_text
    input_ids:
      - filter_original_pages

  - id: train_fasttext_classifier
    config:
      type: train_fasttext
      text_column: cleaned_text
      positive_input_ids:
        - rename_good_pdf_columns
      negative_input_ids:
        - rename_bad_pdf_columns
      dim: 256
      epoch: 3
      lr: 0.1
      word_ngrams: 3
      min_count: 3
      hf_repo_id: mlfoundations-dev/science_pdf_fasttext_classifier_v1
    input_ids:
      - rename_good_pdf_columns
      - rename_bad_pdf_columns
