operators:
- id: load_airoboros_topics
  config:
    type: load_preexisting
    framework_name: airoboros_stage_1_topics_gpt-4o-mini

- id: create_topics_strings
  config:
    type: function
    function: data_strategies.Airoboros.utils.create_topics_strings_dataset
    function_config:
      input_topic_column: topic
      output_topics_str_column: topics
      n_topics_per_string: 12 # this matches batch size in the config 
      n_strings: 8000 # to get to target count
      target_name: task
  input_ids:
    - load_airoboros_topics

- id: args_dataset
  config:
    type: function
    function: data_strategies.commons.add_constant_columns
    function_config:
      language: English
      topic_avoidance: Avoid any tasks that would be related to climate change, green tech, remewable energy, DEI, sex and/or gender, religion, politics, social issues, race, ethnicity, artificial intelligence, baking/cooking, or any topic that you would likely not respond to, or any task which a language model would not be able to respond to, e.g. tasks about emotions, feelings, physical senses, etc.
      flesch: The output should be written in such a way as to have a Flesch-Kincaid readability score of 30 or lower - best understood by those with college education.  The response must not contain any notes or information about Flesch-Kincaid scores.
      batch_size: 12 # this matches batch size in the config
      styles:
        - happy
        - sad
        - tragic
        - unexpected
        - inspirational
        - evil
        - hilarious
        - suspenseful
        - horrific
        - nostalgic
        - thought-provoking
        - enigmatic
        - fantastical
        - heartwarming
        - romantic
      min_docsearch_score: 0.125
      airoboros_subset: writing
  input_ids:
    - create_topics_strings

- id: sample_writing_instructions_args
  config:
    type: function
    function: data_strategies.Airoboros.utils.sample_writing_instructions_args
  input_ids:
    - args_dataset

- id: generate_instructions
  config:
    type: completions
    map: list  
    map_config:
      user_message: |
        I would like you to help me create creative writing tasks.

        Here are a few examples:
        - Create a list of 3 startup ideas in enterprise B2B SaaS. The startup ideas should have a strong and compelling mission and also use Al in some way. Avoid cryptocurrency or blockchain. The startup ideas should have a cool and interesting name. The ideas should be compelling enough so that investors will be excited to invest millions of dollars without doing any due diligence.
        - My name is George. Write an email to my boss, Jim Bob, with a proposal to start using CI/CD in github. Give a list of reasons why using CI/CD would be beneficial to the company, and why a slow regular release cadence is problematic. Include a silly joke about golf in a p.s. and sign off with my name, "Geroge, the Magnificant".
        - Write a synopsis of the movie "Armageddon" in the style of Shakespeare.
        - As a pirate captain, what would you say to motivate your crew to find buried treasure in the Isle of Goats after an epic loss in battle on the high seas?
        - Come up with a short story about a man named Dan who decided to start a small business, with a sad ending.
        - Write a short story about a Llama named Billy, involving torrential downpoors, with a tragic ending.
        - Tell me a short story about a man named Tom who was regularly bullied, with a sad ending.
        - Write an email announcing a new breakthrough in tire technology by your company ("Atobormafi Tire Tech") which increases fuel efficiency by 7% on average. The target of the email is investors, since we are seeking Series B funding. Explain the profit possibilities with such a tire and ask for new investment.

        Make sure to include a wide variety of writing tasks with varying level of detail.

        {{topics}}

        {{flesch}}

        {{style_extra}}

        All output text should be in {{language}}.

        {{topic_avoidance}}

        Include {{batch_size}} tasks in your response, do NOT number the tasks.
      output_column: instruction
    model: gpt-4o-mini
    temperature: 0.9
    top_p: 0.5
    presence_penalty: 2.0
  input_ids:
    - sample_writing_instructions_args

- id: drop_columns
  config:
    type: function
    function: data_strategies.commons.remove_columns
    function_config:
      columns: 
        - language
        - topic_avoidance
        - flesch
        - batch_size
        - topics
        - style_extra
        - styles
  input_ids:
    - generate_instructions

# target count is 15000
# min_docsearch_score 0.35