include_hp: dcft/train/hp_settings/hritik.yaml

dataset_dir: ONLINE
dataset: mlfoundations-dev/physics_250000_samples
template: llama3
messages: conversations
formatting: sharegpt

per_device_train_batch_size: 16      # Can change depending on hardware
gradient_accumulation_steps: 1      # Can change depending on number of GPUs

output_dir: "/tmp/experiments/train/checkpoints/llama3-1_8b_physics_250000_samples"
run_name: llama3-1_8b_physics_250000_samples
hub_model_id: mlfoundations-dev/llama3-1_8b_physics_250000_samples
report_to: wandb
push_to_db: true
push_to_hub: true