include_hp: dcft/train/hp_settings/mistral_sft.yaml

dataset_dir: ONLINE
dataset: mlfoundations-dev/oh-dcft-v3.1-SN-405B-hacky
template: mistral
messages: conversations
formatting: sharegpt

per_device_train_batch_size: 8      # Can change depending on hardware
gradient_accumulation_steps: 8      # Can change depending on number of GPUs

output_dir: "/tmp/experiments/train/checkpoints/oh-dcft-v3.1-SN-405B-hacky"
run_name: mistral_7b_0-3_oh-dcft-v3.1-SN-405B-hacky
hub_model_id: mlfoundations-dev/mistral_7b_0-3_oh-dcft-v3.1-SN-405B-hacky
report_to: wandb
push_to_db: true
push_to_hub: true