name: wi_reasoning_fasttext_training
operators:
  - id: load_positives
    config:
      type: hf_source
      dataset: open-thoughts/OpenThoughts-114k
      split: train
      subset: metadata
      columns: 
        - deepseek_reasoning

  - id: clean_positives
    config:
      type: function
      function: data_strategies.WebInstruct.utils.clean_dataset
      function_config:
        input_column: deepseek_reasoning
        output_column: cleaned_text
    input_ids:
      - load_positives

  - id: load_negatives
    config:
      type: json_source
      directory: /data/horse/ws/rehe951g-p_finetuning/DCLM-baseline-subset
      num_truncate: 100000

  - id: clean_negatives
    config:
      type: function
      function: data_strategies.WebInstruct.utils.clean_dataset
      function_config:
        input_column: text
        output_column: cleaned_text
    input_ids:
      - load_negatives

  - id: train_fasttext_classifier
    config:
      type: train_fasttext
      text_column: cleaned_text
      positive_input_ids:
        - clean_positives
      negative_input_ids:
        - clean_negatives
      dim: 256
      epoch: 5
      lr: 0.1
      word_ngrams: 3
      min_count: 3
      tmp_dir: /data/horse/ws/rehe951g-p_finetuning/tmp
      hf_repo_id: mlfoundations-dev/wi_reasoning_fasttext_training
    input_ids:
      - clean_positives
      - clean_negatives