operators:
- id: load_hf_source
  config:
    type: hf_source
    dataset: EricLu/SCP-116K
    split: train
- id: rename_task_column_positive
  config:
    type: function
    function: data_strategies.commons.force_rename_columns
    function_config:
      column_maps:
        problem: question
  input_ids:
  - load_hf_source

- id: hf_source_bad_seed_cqadupstack
  config:
    type: load_preexisting
    framework_name: cqadupstack_seed_science
- id: hf_source_bad_seed_biology
  config:
    type: load_preexisting
    framework_name: biology_standardized_seed_science
- id: rename_task_column_negative
  config:
    type: function
    function: data_strategies.commons.force_rename_columns
    function_config:
      column_maps:
        problem: question
  input_ids:
  - hf_source_bad_seed_cqadupstack
  - hf_source_bad_seed_biology
- id: train_fasttext_classifier
  config:
    type: train_fasttext
    text_column: question
    positive_input_ids:
      - rename_task_column_positive
    negative_input_ids:
      - rename_task_column_negative
    dim: 256
    epoch: 3
    lr: 0.1
    word_ngrams: 2
    min_count: 3
    hf_repo_id: mlfoundations-dev/instruction_filtering_fast_text_classifier_seed_science_pos_scp
  input_ids:
    - rename_task_column_positive
    - rename_task_column_negative