include_hp: dcft/train/hp_settings/reasoning_7b_5epochs.yaml

dataset_dir: ONLINE
dataset: mlfoundations-dev/OpenThoughts-114k-filter-thought-8192-tokens-conversations-remove-wait-keyword
messages: conversations
formatting: sharegpt
role_tag: from
content_tag: value
user_tag: user
assistant_tag: assistant

per_device_train_batch_size: 1      # Can change depending on hardware
gradient_accumulation_steps: 32      # Can change depending on number of GPUs

output_dir: "/data4/dcft/experiments/train/checkpoints/OpenThoughts-114k-filter-thought-8192-tokens-conversations-remove-wait-keyword"
run_name: OpenThoughts-114k-filter-thought-8192-tokens-conversations-remove-wait-keyword
hub_model_id: mlfoundations-dev/OpenThoughts-114k-filter-thought-8192-tokens-conversations-remove-wait-keyword
report_to: wandb
push_to_db: true
push_to_hub: true