operators:
  - id: args_dataset
    config:
      type: function
      function: data_strategies.commons.create_constant_dataset
      function_config:
        language: English
        batch_size: 10
        min_docsearch_score: 0.05
        airoboros_subset: trivia

  - id: generate_general_instructions
    config:
      type: completions
      map: list_qa
      map_config:
        system_message: "You are a world class trivia AI - provide accurate, succinct responses."
        user_message: |
          I would like you to help me generate random jeopardy/trivia questions. Here are a list of examples:

          What last name starting with 'B' of an uber-cool Hollywood icon is also a verb meaning to hog something, which is way not cool?
          Although this country has more than 300 islands, about 70% of what south pacific country population lives on its largest, Viti Levu?
          Harry Potter might have a better chance of turning metals to gold using what medieval substance from alchemy, also called the tincture?
          A self-titled 1961 L.P. of arias sung by what American Woman great 'L.P.' is known to opera lovers as the 'Blue Album'?
          In what kind of TV place did Commander Sheridan & the gang on 'Babylon 5' live?
          Of Presidents who served, William Henry Harrison & which running mate both fought in the War of 1812?
          Younger musicians inspired by Burt Bacharach include what Brit who collaborated with him on the album 'Painted from Memory'?
          The isthmus of what, also the name of both an ancient & modern city, joins the Peloponnese with the Greek mainland?
          The mysterious Anne Catherick strongly favors a certain color in what novel by Wilkie Collins?
          Vicks VapoRub for cold relief, is a combination of menthol, camphor & what strong-smelling tree oil?
          Football gives us what idiom with 'Run' meaning to remove obstacles for someone else?
          What womans story, Kew Gardens, was illustrated by her sister Vanessa Bell, also a member of the Bloomsbury Group?
          You can't change things, it's what 2-word situation, 'concluded fact' in French?
          Before penicillin, salvarsan, a compound of what poisonous element, was used to treat syphilis?
          In 2021 which New Orleans pianist won an Oscar & released a new album while keeping his day job as Stephen Colbert's bandleader?
          The Apollo 11 astronauts had to declare Moon rocks to which government service upon returning to Earth?
          In 1898 which 'Gift of the Magi' author spent time in the pokey for embezzlement of bank funds?
          With details like the cornucopia, mosaic was a major art form in what era of art made in the Eastern Roman Empire, 400 to 1400 A.D.?

          Generate a set of {{batch_size}} new, unique trivia questions or statements similar to the examples.

          All output text should be in {{language}}.
        output_instruction_column: instruction
        output_response_column: response
      model: gpt-4o-mini
      temperature: 0.7
      top_p: 0.5
      presence_penalty: 2.0
      n_repeat: 16000 # to get to target count
    input_ids:
      - args_dataset

  - id: drop_columns
    config:
      type: function
      function: data_strategies.commons.remove_columns
      function_config:
        columns:
          - language
          - batch_size
    input_ids:
      - generate_general_instructions

# target count is 20000