dataset_dir: ONLINE
dataset: open-thoughts/OpenThoughts-114k
messages: conversations
formatting: sharegpt
role_tag: from
content_tag: value
user_tag: user
assistant_tag: assistant

per_device_train_batch_size: 1      # Can change depending on hardware
gradient_accumulation_steps: 32      # Can change depending on number of GPUs

output_dir: "/data4/dcft/experiments/train/checkpoints/OpenThoughts-114k"
run_name: global_batchsize_1024_laradjusted4
hub_model_id: mlfoundations-dev/global_batchsize_1024_laradjusted4
report_to: wandb
push_to_db: true
push_to_hub: true

### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: dcft/train/zero3.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
template: qwen25
cutoff_len: 16384
overwrite_cache: true
preprocessing_num_workers: 16

### output
logging_steps: 1
save_strategy: epoch
plot_loss: true

### train
global_batch_size: 1024
learning_rate: 0.00016
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000