operators:
- id: seed_math_load_in
  config:
    type: load_preexisting
    framework_name: load_in_math_open2math
- id: calc_embeddings
  config:
    type: function
    sharded: true
    num_shards: 32
    function: data_strategies._B2_Filtering.embedding.apply_embedding_openai
    function_config:
      text_column: instruction_seed
      embedding_column_name: embedding
      split: train
      batch_size: 100
      max_concurrent_requests: 2
      model: text-embedding-3-large
  input_ids:
    - seed_math_load_in

- id: remove_nones
  config:
    type: high_memory_function
    memory: 100 
    sharded: true
    num_shards: 32
    function: data_strategies.commons.remove_nones
    function_config:
      column: embedding
  input_ids:
    - calc_embeddings

- id: load_in_negative_embeddings
  config:
    type: load_preexisting
    framework_name: b2_calc_negative_embeddings_math
- id: remove_nones_negative
  config:
    type: function
    function: data_strategies.commons.remove_nones
    function_config:
      column: embedding
  input_ids:
  - load_in_negative_embeddings
- id: load_in_positive_embeddings
  config:
    type: load_preexisting
    framework_name: b2_calc_positive_embeddings_math
- id: remove_nones_positive
  config:
    type: function
    function: data_strategies.commons.remove_nones
    function_config:
      column: embedding
  input_ids:  
  - load_in_positive_embeddings
- id: force_merge_shards
  config:
    type: function
    function: data_strategies.commons.uniform_sample_fixed
    function_config:
      num_samples: 100000000
  input_ids:
  - remove_nones 
- id: calc_embedding_difference
  config:
    type: generic_resource_function
    num_cpus: 144
    memory: 200
    sharded: true
    num_shards: 32
    function: data_strategies._B2_Filtering.embedding.calc_embedding_score_mean_memory_efficient
    function_config:
      embedding_column: embedding
      positive_embedding_column: embedding
      negative_embedding_column: embedding
    input_dataset_map:
      dataset: remove_nones
      negative_dataset: remove_nones_negative
      positive_dataset: remove_nones_positive
  input_ids:
    - remove_nones
    - remove_nones_negative
    - remove_nones_positive
- id: select_to_be_used
  config:
    type: function
    function: data_strategies._B2_Filtering.utils.filter_top_n
    function_config:
      n: 31_600
      score_column: difference_score
  input_ids:
    - calc_embedding_difference
- id: sample_dataset_final
  config:
    type: function
    function: data_strategies.commons.uniform_sample_fixed
    function_config:
      num_samples: 31_600
  input_ids:
  - select_to_be_used
- id: annotate_r1
  config:
    type: completions
    map: deepseek_reasoner
    map_config:
      input_problem_column: instruction_seed
    model: deepseek-reasoner
    batch: false
    temperature: 1.0
    require_all_responses: false
    backend: openai
    backend_params:
      max_requests_per_minute: 500
      max_tokens_per_minute: 1_000_000_000
      base_url: "https://api.deepseek.com/"
      invalid_finish_reasons: ['content_filter']
  input_ids:
    - sample_dataset_final
- id: convert_reasoning_trace_to_final
  config:
    type: function
    function: data_strategies.commons.convert_reasoning_trace_to_final
    function_config:
      reasoning_column: reasoning
      solution_column: deepseek_solution
      output_column: final_reasoning_trace
  input_ids:
  - annotate_r1
- id: convert_to_sharegpt
  config:
    type: function
    function: data_strategies.commons.convert_instruction_response_to_sharegpt
    function_config:
      input_instruction_column: instruction_seed
      input_response_column: final_reasoning_trace
      output_sharegpt_column: conversations
  input_ids:
    - convert_reasoning_trace_to_final
