dataset_dir: ONLINE
dataset: mlfoundations-dev/openthoughts_1000
messages: conversations
formatting: sharegpt
role_tag: from
content_tag: value
user_tag: user
assistant_tag: assistant

per_device_train_batch_size: 1      # Can change depending on hardware
gradient_accumulation_steps: 8      # Can change depending on number of GPUs

output_dir: "/data4/dcft/experiments/train/checkpoints/openthoughts_1000"
run_name: 1k_globalbatchsize64_lr1e5_epochs5
hub_model_id: mlfoundations-dev/1k_globalbatchsize64_lr1e5_epochs5
report_to: wandb
push_to_db: true
push_to_hub: true

### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: dcft/train/zero3.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
enable_liger_kernel: true

### dataset
template: qwen25
cutoff_len: 16384
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_persistent_workers: true
dataloader_pin_memory: true
dataloader_num_workers: 4

### output
logging_steps: 1
save_strategy: epoch
plot_loss: true

### train
global_batch_size: 64
learning_rate: 1.0e-5
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000