### preset
include_hp: dcft/train/hp_settings/simpo.yaml

### model
model_name_or_path: "google/gemma-2-9b-it"

### train
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
gradient_accumulation_steps: 2

### dataset
dataset: cdc0b2d9-493b-4cb1-87e8-8fb1e3f4b247
dataset_dir: DATABASE
template: gemma
formatting: sharegpt
ranking: true
messages: conversations
chosen: chosen
rejected: rejected

### output
output_dir: "experiments/train/checkpoints/gemma-oh-preferences"

## reporting
report_to: wandb
run_name: gemma-oh-preferences
push_to_db: true
push_to_hub: true
hub_model_id: mlfoundations-dev/gemma-oh-preferences