include_hp: dcft/train/hp_settings/reasoning.yaml

dataset_dir: ONLINE
dataset: mlfoundations-dev/arxiv_biology_seed_science
messages: conversations
formatting: sharegpt
role_tag: from
content_tag: value
user_tag: user
assistant_tag: assistant

per_device_train_batch_size: 1      # Can change depending on hardware
gradient_accumulation_steps: 3      # Can change depending on number of GPUs

output_dir: "/leonardo_work/EUHPC_E03_068/eguha/DCFT_experiments/checkoints/DCFT-arxiv_biology_seed_science-etash"
run_name: DCFT-arxiv_biology_seed_science-etash
hub_model_id: mlfoundations-dev/DCFT-arxiv_biology_seed_science-etash
report_to: wandb
push_to_db: false
push_to_hub: false
output_dir: /leonardo_work/EUHPC_E03_068/eguha/checkoints/arxiv_biology_seed_science

deepspeed: dcft/train/zero3_offload.json
do_train: true
enable_liger_kernel: true
ddp_timeout: 180000000
use_unsloth_gc: true
flash_attn: fa2