assistant_tag: assistant
bf16: true
content_tag: value
cutoff_len: 16384
dataset: /leonardo_work/EUHPC_E03_068/DCFT_shared/datasets/datasets--mlfoundations-dev--ot-114k_Math-Raw-all-correct/snapshots/11ee776856a49ce976c3bfa580c9e01eccfd924f
dataset_dir: ONLINE
ddp_timeout: 180000000
deepspeed: dcft/train/zero3_offload.json
do_train: true
enable_liger_kernel: true
finetuning_type: full
flash_attn: fa2
formatting: sharegpt
global_batch_size: 256
gradient_accumulation_steps: 1
hub_model_id: mlfoundations-dev/mlfoundations-dev_ot-114k_Math-Raw-all-correct_Qwen_Qwen2.5-7B-Instruct_open_thoughts_template
learning_rate: 1.0e-05
logging_steps: 1
lr_scheduler_type: cosine
max_samples: 1000000
messages: conversations
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
num_train_epochs: 3.0
output_dir: /leonardo_work/EUHPC_E03_068/DCFT_shared/outputs/mlfoundations-dev_ot-114k_Math-Raw-all-correct_Qwen_Qwen2.5-7B-Instruct_open_thoughts_template
overwrite_cache: true
per_device_train_batch_size: 1
plot_loss: true
preprocessing_num_workers: 16
push_to_db: false
push_to_hub: false
report_to: wandb
role_tag: from
run_name: mlfoundations-dev_ot-114k_Math-Raw-all-correct_Qwen_Qwen2.5-7B-Instruct_open_thoughts_template
save_steps: 50
stage: sft
template: llama3
tokenized_path: /leonardo_work/EUHPC_E03_068/tvu00001/lf_datasets/mlfoundations-dev/stratos_verified_mix_tokenized
use_unsloth_gc: true
user_tag: user
warmup_ratio: 0.1
