assistant_tag: assistant
bf16: true
content_tag: value
cutoff_len: 16384
dataset: /leonardo_work/EUHPC_E03_068/DCFT_shared/datasets/datasets--mlfoundations-dev--HeroRun1/snapshots/689ce4065bc16709c98d90c349ac3a47033cc948
dataset_dir: ONLINE
ddp_timeout: 180000000
deepspeed: dcft/train/zero3_offload.json
do_train: true
enable_liger_kernel: true
finetuning_type: full
flash_attn: fa2
formatting: sharegpt
global_batch_size: 256
gradient_accumulation_steps: 1
hub_model_id: mlfoundations-dev/DCFT-Stratos-Verified-114k-Llama-3_3-70B
learning_rate: 1.0e-05
logging_steps: 1
lr_scheduler_type: cosine
max_samples: 1000000
messages: conversations
model_name_or_path: /leonardo_work/EUHPC_E03_068/DCFT_shared/models/models--meta-llama--Llama-3.1-8B-Instruct/snapshots/0e9e39f249a16976918f6564b8830bc894c89659
num_train_epochs: 3.0
output_dir: /leonardo_work/EUHPC_E03_068/DCFT_shared/outputs/mlfoundations-dev_HeroRun1_meta-llama_Llama-3.1-8B-Instruct_open_thoughts_template
overwrite_cache: true
per_device_train_batch_size: 1
plot_loss: true
preprocessing_num_workers: 16
push_to_db: false
push_to_hub: false
report_to: wandb
role_tag: from
run_name: mlfoundations-dev_HeroRun1_meta-llama_Llama-3.1-8B-Instruct_open_thoughts_template
save_steps: 50
stage: sft
template: llama3
tokenized_path: /leonardo_work/EUHPC_E03_068/tvu00001/lf_datasets/mlfoundations-dev/stratos_verified_mix_tokenized
use_unsloth_gc: true
user_tag: user
warmup_ratio: 0.1
