assistant_tag: assistant
content_tag: value
dataset: mlfoundations-dev/hero_run_2_fix_conversations
dataset_dir: ONLINE
datasets_cache_dir: /leonardo_work/EUHPC_E03_068/DCFT_shared/hf_cache/datasets
ddp_timeout: 180000000
deepspeed: dcft/train/zero3_offload.json
do_train: true
enable_liger_kernel: true
flash_attn: fa2
formatting: sharegpt
gradient_accumulation_steps: 3
hub_model_id: mlfoundations-dev/DCFT-arxiv_biology_seed_science-etash
include_hp: dcft/train/hp_settings/reasoning.yaml
messages: conversations
model_name_or_path: /leonardo_work/EUHPC_E03_068/DCFT_shared/hf_cache/models/models--Qwen--Qwen2.5-7B-Instruct/snapshots/a09a35458c702b33eeacc393d103063234e8bc28
output_dir: /leonardo_work/EUHPC_E03_068/DCFT_shared/outputs/mlfoundations-dev_hero_run_2_fix_conversations_Qwen_Qwen2.5-7B-Instruct_generic_reasoning
per_device_train_batch_size: 1
push_to_db: false
push_to_hub: false
report_to: wandb
role_tag: from
run_name: mlfoundations-dev_hero_run_2_fix_conversations_Qwen_Qwen2.5-7B-Instruct_generic_reasoning
use_unsloth_gc: true
user_tag: user
