assistant_tag: assistant
bf16: true
content_tag: value
cutoff_len: 16384
dataset: /leonardo_work/EUHPC_E03_068/marianna/lf_datasets/mlfoundations-dev/stratos_verified_mix
dataset_dir: ONLINE
output_dir: /leonardo_work/EUHPC_E03_068/tvu00001/DCFT_experiments/OpenThoughts-70b-bs-256
ddp_timeout: 180000000
deepspeed: dcft/train/zero3_offload.json
do_train: true
enable_liger_kernel: true
finetuning_type: full
formatting: sharegpt
global_batch_size: 64
gradient_accumulation_steps: 1
hub_model_id: mlfoundations-dev/DCFT-Stratos-Verified-114k-Llama-3_3-70B
learning_rate: 5.0e-05
logging_steps: 1
lr_scheduler_type: cosine
max_samples: 1000000
messages: conversations
model_name_or_path: /leonardo_work/EUHPC_E03_068/marianna/models/meta-llama/Llama-3.3-70B-Instruct
num_train_epochs: 3.0
overwrite_cache: true
per_device_train_batch_size: 1
plot_loss: true
preprocessing_num_workers: 16
push_to_db: false
push_to_hub: false
report_to: wandb
role_tag: from
run_name: DCFT-Stratos-Verified-114k-70B
save_steps: 50
stage: sft
template: llama3
tokenized_path: /leonardo_work/EUHPC_E03_068/tvu00001/lf_datasets/mlfoundations-dev/stratos_verified_mix_tokenized
user_tag: user
warmup_ratio: 0.1
