include_hp: dcft/train/hp_settings/reasoning.yaml

dataset_dir: ONLINE
dataset: mlfoundations-dev/s1K_reformat
messages: conversations
formatting: sharegpt
role_tag: from
content_tag: value
user_tag: human
assistant_tag: gpt

per_device_train_batch_size: 1      # Can change depending on hardware
gradient_accumulation_steps: 3      # Can change depending on number of GPUs

output_dir: "/data4/dcft/experiments/train/checkpoints/s1K_reformat"
run_name: s1K_reformat
hub_model_id: mlfoundations-dev/s1K_reformat_v2
report_to: wandb
push_to_db: true
push_to_hub: true
