operators:
- id: load_hf_source
  config:
    type: hf_source
    dataset: allenai/sciq
    split: train
- id: rename_task_column_positive
  config:
    type: function
    function: data_strategies.commons.force_rename_columns
    function_config:
      column_maps:
        question: instruction_seed
  input_ids:
  - load_hf_source
- id: decontaminate
  config:
    type: cpu_function
    sharded: false
    num_cpus: 32
    function:  data_strategies._A1_Source.utils.decontaminate_fuzzy_w_ngram
    function_config:
      column: instruction_seed
      eval_datasets:
        - HuggingFaceH4/MATH-500
        - Maxwell-Jia/AIME_2024
        - AI-MO/aimo-validation-amc
        - livecodebench/code_generation_lite
        - mlfoundations-dev/AIME2025_combined
        - cais/hle
        - open-r1/codeforces
        - Idavidrein/gpqa
        - daman1209arora/jeebench
        - mlfoundations-dev/mmlu_pro_eval_full
        - Qwen/CodeElo
        - open-r1/ioi
      eval_columns:
        - problem
        - Problem
        - problem
        - question_content
        - question
        - question
        - description
        - Question
        - question
        - prompt
        - description
        - statement
      eval_splits:
        - test
        - train
        - train
        - test
        - train
        - test
        - test
        - train
        - test
        - test
        - test
        - test
      eval_subsets:
        Idavidrein/gpqa: gpqa_diamond
      similarity_threshold: 75.0
      ngram_size: 13
  input_ids:
  - rename_task_column_positive
- id: calc_embeddings_positive
  config:
    type: function
    function: data_strategies._B2_Filtering.embedding.apply_embedding_openai
    function_config:
      text_column: instruction_seed
      embedding_column_name: embedding
      split: train
      batch_size: 100
      max_concurrent_requests: 100
      model: text-embedding-3-large
  input_ids:
    - decontaminate