operators:
- id: load_in
  config:
    type: load_preexisting
    framework_name: load_in_science_stackexchange_physics
- id: calc_embeddings
  config:
    type: function
    sharded: true
    num_shards: 32
    function: data_strategies._B2_Filtering.embedding.apply_embedding_openai
    function_config:
      text_column: instruction_seed
      embedding_column_name: embedding
      split: train
      batch_size: 100
      max_concurrent_requests: 2
      model: text-embedding-3-large
  input_ids:
    - load_in

- id: remove_nones
  config:
    type: function
    function: data_strategies.commons.remove_nones
    function_config:
      column: embedding
  input_ids:
  - calc_embeddings
- id: load_in_negative_embeddings
  config:
    type: load_preexisting
    framework_name: b2_calc_negative_embeddings_science
- id: remove_nones_negative
  config:
    type: function
    function: data_strategies.commons.remove_nones
    function_config:
      column: embedding
  input_ids:
  - load_in_negative_embeddings
- id: load_in_positive_embeddings
  config:
    type: load_preexisting
    framework_name: b2_calc_positive_embeddings_science
- id: remove_nones_positive
  config:
    type: function
    function: data_strategies.commons.remove_nones
    function_config:
      column: embedding
  input_ids:
  - load_in_positive_embeddings
- id: calc_embedding_difference
  config:
    type: generic_resource_function
    num_cpus: 8
    memory: 200
    sharded: true
    num_shards: 100
    function: data_strategies.InstructionFiltering.EmbeddingFilter.utils.calc_embedding_score_mean
    function_config:
      embedding_column: embedding
      positive_embedding_column: embedding
      negative_embedding_column: embedding
    input_dataset_map:
      dataset: remove_nones
      negative_dataset: remove_nones_negative
      positive_dataset: remove_nones_positive
  input_ids:
    - remove_nones
    - remove_nones_negative
    - remove_nones_positive
- id: select_to_be_used
  config:
    type: function
    function: data_strategies._B2_Filtering.utils.filter_top_n
    function_config:
      n: 15_800
      score_column: difference_score
  input_ids:
    - calc_embedding_difference
- id: sample_dataset_final
  config:
    type: function
    function: data_strategies.commons.uniform_sample_fixed
    function_config:
      num_samples: 15_800
  input_ids:
  - select_to_be_used