### model
model_name_or_path: "mistralai/Mistral-7B-v0.3"

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: dcft/train/zero3.json
packing: true
neat_packing: true
enable_liger_kernel: false

### dataset
template: mistral
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### output
save_strategy: epoch
logging_steps: 10
plot_loss: true
overwrite_output_dir: true

### train
adam_beta1: 0.9
adam_beta2: 0.999
max_grad_norm: 1

global_batch_size: 512              # Do not change this
gradient_checkpointing: true
learning_rate: 5.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine_with_min_lr
warmup_ratio: 0.05
lr_scheduler_kwargs: {min_lr: 5.0e-7}
bf16: true
weight_decay: 0.1
ddp_timeout: 180000000

### eval
val_size: 0.05
eval_strategy: epoch