### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: dcft/train/zero3.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
enable_liger_kernel: true
packing: true
neat_packing: true

### dataset
template: qwen25
cutoff_len: 16384
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_persistent_workers: true
dataloader_pin_memory: true
dataloader_num_workers: 4

### output
logging_steps: 1
save_strategy: epoch
plot_loss: true

### train
global_batch_size: 512
learning_rate: 8.0e-5
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000