include_hp: dcft/train/hp_settings/reasoning.yaml

dataset_dir: ONLINE
dataset: qihoo360/Light-R1-SFTData
messages: conversations
formatting: sharegpt
role_tag: from
content_tag: value
user_tag: user
assistant_tag: assistant

per_device_train_batch_size: 1      # Can change depending on hardware
gradient_accumulation_steps: 16      # Can change depending on number of GPUs

output_dir: "/data4/dcft/experiments/train/checkpoints/Light-R1-SFTData"
run_name: Light-R1-SFTData
hub_model_id: mlfoundations-dev/Light-R1-SFTData
report_to: wandb
push_to_db: true
push_to_hub: true