include_hp: dcft/train/hp_settings/reasoning.yaml

dataset_dir: ONLINE
dataset: secemp9/instruction_solution_thought
messages: messages
formatting: sharegpt
role_tag: role
content_tag: content
user_tag: user
assistant_tag: assistant

per_device_train_batch_size: 1      # Can change depending on hardware
gradient_accumulation_steps: 4      # Can change depending on number of GPUs

output_dir: "/data4/dcft/experiments/train/checkpoints/traceback"
run_name: traceback
hub_model_id: mlfoundations-dev/traceback
report_to: wandb
push_to_db: true
push_to_hub: true