operators:
- id: load_airoboros_topics
  config:
    type: load_preexisting
    framework_name: airoboros_stage_1_topics_gpt-4o-mini

- id: create_topics_strings
  config:
    type: function
    function: data_strategies.Airoboros.utils.create_topics_strings_dataset
    function_config:
      input_topic_column: topic
      output_topics_str_column: topics
      n_topics_per_string: 10 # this matches batch size in the config (10)
      n_strings: 1000 # to get to target count
      target_name: instruction
  input_ids:
    - load_airoboros_topics

- id: args_dataset
  config:
    type: function
    function: data_strategies.commons.add_constant_columns
    function_config:
      language: English
      topic_avoidance: Avoid any tasks that would be related to climate change, green tech, remewable energy, DEI, sex and/or gender, religion, politics, social issues, race, ethnicity, artificial intelligence, baking/cooking, or any topic that you would likely not respond to, or any task which a language model would not be able to respond to, e.g. tasks about emotions, feelings, physical senses, etc.
      flesch: The output should be written in such a way as to have a Flesch-Kincaid readability score of 30 or lower - best understood by those with college education.  The response must not contain any notes or information about Flesch-Kincaid scores.
      batch_size: 10
      min_docsearch_score: 0.1
      airoboros_subset: general
  input_ids:
    - create_topics_strings

- id: generate_general_instructions
  config:
    type: completions
    map: list  
    map_config:
      user_message: |
        I would like you to help me create a list of diverse tasks.

        Requirements for the tasks:
        - Do not repeat the verb for each task to maximize diversity.
        - The list of tasks should include a variety of types of prompts, such as general knowledge questions, brainstorming, classification, editing, riddles, role-playing, etc.
        - Do not include any coding or math tasks.
        - Each task must be something a large language model can complete with a text-only response without any access to the internet. For example do not create a task asking to create or use visual/audio output, setting an alarm, scheduling something on the calendar, read content from a website, etc. because the language model cannot perform those tasks.
        - Each instruction should be in {{language}}.
        - {{topic_avoidance}}
        - One of the tasks should be highly complex, including 3 or more criteria.
        - One of the tasks should ask for output in a randomly specified format, such as a numbered list, bullet points, JSON, markdown, CSV, YAML, python dict, etc.
        - Any instruction referencing a list of objects, such as classifying a list of items, should include the list of items.
        {{topics}}

        {{flesch}}

        Include exactly {{batch_size}} tasks in your response.
      output_column: instruction
    model: gpt-4o
    temperature: 0.7
    top_p: 0.5
    presence_penalty: 2.0
  input_ids:
    - args_dataset

- id: drop_columns
  config:
    type: function
    function: data_strategies.commons.remove_columns
    function_config:
      columns: 
        - language
        - topic_avoidance
        - flesch
        - batch_size
        - topics
  input_ids:
    - generate_general_instructions

# target count is 10000

