include_hp: dcft/train/hp_settings/hritik.yaml

dataset_dir: ONLINE
dataset: mlfoundations-dev/oh_v1-2_only_slim_orca
template: llama3
messages: conversations
formatting: sharegpt

per_device_train_batch_size: 2      # Can change depending on hardware
gradient_accumulation_steps: 32      # Can change depending on number of GPUs

output_dir: "experiments/train/checkpoints/oh_v1-2_only_slim_orca"
run_name: oh_v1-2_only_slim_orca
hub_model_id: mlfoundations-dev/oh_v1-2_only_slim_orca
report_to: wandb
push_to_db: true
push_to_hub: true
