include_hp: dcft/train/hp_settings/qwen_sft.yaml

dataset_dir: ONLINE
dataset: mlfoundations-dev/bespokelabs-Stratos-50k
messages: conversations
formatting: sharegpt
role_tag: from
content_tag: value
user_tag: user
assistant_tag: assistant

per_device_train_batch_size: 8      # Can change depending on hardware
gradient_accumulation_steps: 2      # Can change depending on number of GPUs

output_dir: "/data4/dcft/experiments/train/checkpoints/bespokelabs-Stratos-50k"
run_name: bespokelabs-Stratos-50k
hub_model_id: mlfoundations-dev/bespokelabs-Stratos-50k
report_to: wandb
push_to_db: true
push_to_hub: true
