include_hp: dcft/train/hp_settings/reasoning.yaml

dataset_dir: ONLINE
dataset: mlfoundations-dev/openthoughts-114k-no-special-template
messages: conversations
formatting: sharegpt
role_tag: from
content_tag: value
user_tag: user
assistant_tag: assistant

per_device_train_batch_size: 1      # Can change depending on hardware
gradient_accumulation_steps: 3      # Can change depending on number of GPUs

output_dir: "/data4/dcft/experiments/train/checkpoints/openthoughts-114k-no-special-template"
run_name: openthoughts-114k-no-special-template
hub_model_id: mlfoundations-dev/openthoughts-114k-no-special-template
report_to: wandb
push_to_db: true
push_to_hub: true
