### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: dcft/train/zero3_offload.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

messages: conversations
formatting: sharegpt
role_tag: from
content_tag: value
user_tag: user
assistant_tag: assistant


### dataset
dataset: bespokelabs/Bespoke-Stratos-17k
dataset_dir: ONLINE
template: qwen25
cutoff_len: 16384
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/Stratos-R1-7B-DCFT
logging_steps: 1
save_steps: 100
plot_loss: true

### train
global_batch_size: 96
per_device_train_batch_size: 1
gradient_accumulation_steps: 12
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

report_to: wandb
run_name: Bespoke-Stratos-17k
hub_model_id: mlfoundations-dev/Bespoke-Stratos-17k-v4
push_to_db: true
push_to_hub: true
