operators:
- id: args_dataset
  config:
    type: function
    function: data_strategies.commons.create_constant_dataset
    function_config:
      language: English
      batch_size: 10
      coding_languages:
        - python
        - javascript
        - java
        - c
        - c++
        - golang
        - C#
        - bash
        - powershell
        - SQL
      related_software:
        - elasticsearch
        - opensearch
        - mongodb
        - cassandra
        - redis
        - memcached
        - postgresql
        - mariadb
        - mysql
        - aws s3
        - gcs cloud storage
        - azure storage
        - aws lambda
        - kubernetes
        - pytorch
        - pandas
        - numpy
        - keras
        - tensorflow
        - scipy
        - matplotlib
        - django
        - cherrypy
        - swagger/openapi
        - pyramid web framework
      min_docsearch_score: 0.04
      airoboros_subset: coding

- id: sample_coding_instructions_args
  config:
    type: function
    function: data_strategies.Airoboros.utils.sample_coding_instructions_args
    function_config:
      n_samples: 2400 # Use this to control the output size
  input_ids:
    - args_dataset

- id: generate_instructions
  config:
    type: completions
    map: list
    map_config:
      user_message: |
        I would like you to help me create a set of coding and/or scripting tasks.

        Here are a few example tasks:
        Example: 
        Write an async python FastAPI server. The webserver should support command line arguments for port, listening IP, and a static directory to serve files from and save files to. In addition to static files, the webserver should support an upload endpoint, which saves files to the specified directory, using the sha256 hexdigest of the content for the file name. If the file already exists, the upload should be discarded. In addition, there should be an endpoint to list all files and get a file by ID.

        Example: 
        Create a python model for "Person" that would work well in a workplace context, along with validators, and a way to fetch remote information related to the person such as social media profiles/content. Be sure to include a profile image with remote file and crop/resize support.

        Example: 
        Implement the B*tree algorithm in Javascript.

        Example: 
        Write a solution to Djikstra's algorithm in GoLang.

        Example: 
        Create an ascii snake game in Python, without any graphical libraries.

        Example: 
        Create a text-based solitaire implementation using python. Here are some additional requirements:
        - The game state should be saved to mariadb.
        - The game should take a screenshot after each move as a record.
        - The game should accept keyboard input only, not mouse.

        Example: 
        Create a python script with the following:
        a. Accepts a single word as input.
        b. If the user inputs more than one word, or the word is more than 10 characters, print an error message and stop.
        c. Generate a large ascii art version of the input word.

        The tasks must be something a coding language model can complete without access to additional resources.

        The tasks must be something that could be completed with 2000 words and symbols or less.

        {{coding_languages}}

        The tasks should be in {{language}}.

        Don't prefix the tasks with the language, simply include the language to be used somewhere in the wording of the task.

        {{related_software}}

        None of the tasks should be about reading from or writing to csvs.

        Give me {{batch_size}} new coding tasks. Do not number the tasks, just provide the tasks.
      output_column: instruction
    model: gpt-4o-mini
    temperature: 0.7
    top_p: 0.5
    presence_penalty: 2.0
  input_ids:
    - sample_coding_instructions_args

- id: drop_columns
  config:
    type: function
    function: data_strategies.commons.remove_columns
    function_config:
      columns: 
        - language
        - batch_size
        - coding_languages
        - related_software
  input_ids:
    - generate_instructions

# target count is 12000
