operators:
- id: hf_source_taco
  config:
    type: hf_source
    dataset: mlfoundations-dev/bespokelabs-sky-t1-taco-rejection-sampled
    split: train

- id: hf_source_leetcode
  config:
    type: hf_source
    dataset: Asap7772/leetcode-rosetta-processed-with-test-cases
    split: train
- id: rename_task_column_leetcode
  config:
    type: function
    function: data_strategies.commons.force_rename_columns
    function_config:
      column_maps:
        content: question
  input_ids:
  -  hf_source_leetcode



- id: hf_source_bad_seed_code_reflect
  config:
    type: load_preexisting
    framework_name: reflection
- id: hf_source_bad_seed_code_octo
  config:
    type: load_preexisting
    framework_name: octopack_sft
- id: rename_task_column
  config:
    type: function
    function: data_strategies.commons.force_rename_columns
    function_config:
      column_maps:
        instruction_seed: question
  input_ids:
  - hf_source_bad_seed_code_octo
  - hf_source_bad_seed_code_reflect
- id: train_fasttext_classifier
  config:
    type: train_fasttext
    text_column: question
    positive_input_ids:
      - rename_task_column_leetcode
      - hf_source_taco
    negative_input_ids:
      - rename_task_column
    dim: 256
    epoch: 3
    lr: 0.1
    word_ngrams: 2
    min_count: 3
    hf_repo_id: mlfoundations-dev/instruction_filtering_fast_text_code_pos_leetcode_taco_neg_reflection_octopack
  input_ids:
    - rename_task_column_leetcode
    - hf_source_taco
    - rename_task_column