include_hp: dcft/train/hp_settings/hritik.yaml

dataset_dir: ONLINE
dataset: mlfoundations-dev/stackexchange_cseducators
messages: conversations
formatting: sharegpt

per_device_train_batch_size: 8      # Can change depending on hardware
gradient_accumulation_steps: 8      # Can change depending on number of GPUs

output_dir: "/data4/dcft/experiments/train/checkpoints/stackexchange_cseducators"
run_name: stackexchange_cseducators
hub_model_id: mlfoundations-dev/stackexchange_cseducators
report_to: wandb
push_to_db: true
push_to_hub: true
