dataset_dir: ONLINE
dataset: mlfoundations-dev/herorun_1_1
messages: conversations
formatting: sharegpt
role_tag: from
content_tag: value
user_tag: user
assistant_tag: assistant

per_device_train_batch_size: 1      # Can change depending on hardware
gradient_accumulation_steps: 1      # Can change depending on number of GPUs

output_dir: "/data4/dcft/experiments/train/checkpoints/herorun_1_1"
run_name: herorun_1_1_3epoch
hub_model_id: mlfoundations-dev/herorun_1_1_3epoch
report_to: wandb
push_to_db: true
push_to_hub: true


### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: dcft/train/zero3.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
enable_liger_kernel: true
packing: true
neat_packing: true


### dataset
template: qwen25
cutoff_len: 16384
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
logging_steps: 1
save_strategy: epoch
plot_loss: true

### train
global_batch_size: 96
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 1800000000

dataloader_persistent_workers: true
dataloader_pin_memory: true
dataloader_num_workers: 4