### preset
include_hp: dcft/train/hp_settings/simpo.yaml

### model
model_name_or_path: "bespokelabs/Bespoke-Stratos-7B"

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
per_device_eval_batch_size: 1

### dataset
dataset: mlfoundations-dev/dpo_from_multiple_samples_shortest_numina_aime
dataset_dir: ONLINE
template: qwen25
formatting: sharegpt
ranking: true
messages: conversations
chosen: chosen
rejected: rejected

### output
output_dir: "experiments/train/checkpoints/dpo_from_multiple_samples_shortest_numina_aime"

## reporting
report_to: wandb
run_name: dpo_from_multiple_samples_shortest_numina_aime
push_to_db: true
push_to_hub: true
hub_model_id: mlfoundations-dev/dpo_from_multiple_samples_shortest_numina_aime