include_hp: dcft/train/hp_settings/hritik_no_model.yaml
model_name_or_path: "mlfoundations-dev/oh-dcft-v3.1-gpt-4o-mini"

dataset_dir: ONLINE
dataset: mlfoundations-dev/openo1_sft_original
template: llama3

per_device_train_batch_size: 8      # Can change depending on hardware
gradient_accumulation_steps: 8      # Can change depending on number of GPUs

output_dir: "./experiments/train/checkpoints/open_o1_sft_original_plus_oh_v3.1"
run_name: open-o1-sft-original-plus-oh
hub_model_id: mlfoundations-dev/open-o1-sft-original-plus-oh-v3.1
report_to: wandb
push_to_db: true
push_to_hub: true